services:
  rabbitMq:
    image: rabbitmq:3.10-management
    container_name: rabbitmq-container
    restart: always
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
        - ${DATA_PATH_HOST}/rabbitmq:/var/lib/rabbitmq/
    environment:   
        - RABBITMQ_DEFAULT_USER=admin
        - RABBITMQ_DEFAULT_PASS=admin
        - RABBITMQ_BASE=./dados
 








    